version: '2'
services:

    application:
        build: ./docker/code
        volumes:
            - ./backend:/var/www/backend
            - ./logs/backend:/var/www/backend/storage/logs
        tty: true
        networks:
         - chubbnet
    
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: backend
            MYSQL_USER: backend
            MYSQL_PASSWORD: backend
        networks:
         - chubbnet

    php:
        build: ./docker/php-fpm
        ports:
            - "9000:9000"
        volumes_from:
            - application
        links:
            - db
        networks:
            - chubbnet
        
    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - application
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
        environment:
              - TARGET=localhost
        networks:
         - chubbnet

    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./docker/elk/logstash:/etc/logstash:cached
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns:cached
        volumes_from:
            - application
            - php
            - nginx
        networks:
         - chubbnet

    node:
        build: ./docker/node
        ports:
            - "8080:8080"
        volumes_from:
           - nginx
        networks:
            - chubbnet

networks:
  chubbnet:
    driver: "bridge"

