#FROM node:10
FROM tiangolo/node-frontend:10 as build-stage

MAINTAINER MiguelPlazasR <miguelplazasr@gmail.com>

#WORKDIR /var/www/crux
#
#COPY . .

#COPY package*.json /app/

RUN ls -la

#WORKDIR /var/www/crux
#

#COPY . .
#
#RUN npm install

#COPY . .
#
#ARG configuration=production
#
##RUN npm run build -- --output-path=./dist/out --configuration $configuration
#
#EXPOSE 8080
#CMD [ "npm", "start" ]